export default  () => ({
  support_themes:[],
  messages:[],
  active_theme_id:null,
  active_status:null,
  ticket_total:0,
  ticket_theme_title:'',
  users_page:1,
  users_per_page:10,
  users_last_page:2,
  support_themes_answer_page:1,
  support_themes_answer_per_page:10,
  support_themes_answer_last_page:2,
  ticket_conversations_page:1,
  ticket_conversations_per_page:10,
  ticket_conversations_last_page:2,
  conversation_messages_page:1,
  conversation_messages_per_page:10,
  conversation_messages_last_page:2,
  conversation_messages_identifier:1,
  support_themes_answer_last_identifier: 1,
  user_chat_sidebar_identifier: 1,
  chat_users_list: [],
  ticket_conversations_users_list: [],
  active_ticket_id:null,
  active_conversation_id:null,
  number:null,
  chatTopUserData:[],
  support_themes_answer_list:[],
  searchQuery:{},
  close:0,
  new:1,
  expectation:2,
  viewed:3,
  lastMessage:null,
  apply_flag:false,
  all_messages_unread_count:0,
  switchers : [
    {
      value: 'New (+313)',
      text: 'New',
      counter: 0,
      status:1,
      checked: true
    },
    {
      value: 'Viewed (313)',
      text: 'Viewed',
      status:3,
      counter: 0,
    },
    {
      value: 'Expectation (14)',
      text: 'Expectation',
      status:2,
      counter: 0,
    },
    {
      value: 'Close (313)',
      text: 'Close',
      status:0,
      counter: 0,
    },
  ]
})


